#!/usr/bin/with-contenv bash

set -e

mkdir -p /data
chown abc:abc /data

config="/data/Rocket.toml"

# always copy fresh template so env var changes take effect on restart
cp /default/Rocket.toml "$config"

PORT=${PORT:-8080}
BIND=${BIND:-0.0.0.0}

# global
sed -i "s#%%PORT%%#${PORT}#g" "$config"
sed -i "s#%%BIND%%#${BIND}#g" "$config"

# production
sed -i "s#%%BASE_URI%%#${BASE_URI}#g" "$config"
sed -i "s#%%TOKEN_SECRET%%#${TOKEN_SECRET}#g" "$config"

if [[ -n "$FROM_EMAIL" ]]; then
  sed -i "s#%%FROM_EMAIL%%#${FROM_EMAIL}#g" "$config"
else
  echo "WARNING: FROM_EMAIL is not set, removing placeholder from config"
  sed -i "s#%%FROM_EMAIL%%##g" "$config"
fi

# fix branding
if [[ -n "$HOST" ]]; then
  grep -rln "keys.openpgp.org" /app/dist/ | xargs -r -d '\n' sed -i "s#keys\\.openpgp\\.org#${HOST}#g"
fi
